# Site settings
title: "MyResearchNotes"
description: "Exploring the frontiers of AI research and applications"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title/
paginate: 9
paginate_path: "/page:num/"

# Author settings
author:
  name: Research Team
  email: contact@example.com

# Collections
collections: []

# Default settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Research Team"
      comments: false

# Social settings
twitter_username: myresearchnotes
github_username: myresearchnotes
linkedin_username: myresearchnotes

# SEO settings
twitter:
  username: myresearchnotes
  card: summary_large_image
logo: /assets/images/logo.png

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
