title: "MyResearchNotes"
description: "Exploring the frontiers of AI research and applications"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
paginate: 9
paginate_path: "/page:num/"
permanent_links: /:categories/:title/

# Default front matter for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Research Team"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Social settings for SEO
twitter_username: myresearchnotes
github_username: myresearchnotes

# Collections
collections: []