# Update this value to your GitHub Pages URL, e.g.
# "https://<USERNAME>.github.io/<REPOSITORY>/" if hosting as a project page.
baseURL = "https://example.github.io/"
title = "MyResearchNotes"
languageCode = "en-us"
theme = "hugo-PaperMod"

# Number of posts per page
[pagination]
  pagerSize = 9


[params]
  description = "Exploring the frontiers of AI research and applications"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  homeInfoParams = { Title = "Welcome", Content = "Exploring the frontiers of AI research and applications" }

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/myresearchnotes"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/myresearchnotes"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/myresearchnotes"
