baseURL = "/"
title = "MyResearchNotes"
languageCode = "en-us"

[pagination]
  pagerSize = 9

[params]
  description = "Exploring the frontiers of AI research and applications"
  twitter = "myresearchnotes"
  github = "myresearchnotes"
  linkedin = "myresearchnotes"
