# Update this value to your GitHub Pages URL, e.g.
# "https://<USERNAME>.github.io/<REPOSITORY>/" if hosting as a project page.
baseURL = "https://example.github.io/"
title = "MyResearchNotes"
languageCode = "en-us"

[pagination]
  pagerSize = 9

[params]
  description = "Exploring the frontiers of AI research and applications"
  twitter = "myresearchnotes"
  github = "myresearchnotes"
  linkedin = "myresearchnotes"
