baseURL = "https://13ryanC.github.io/"   # ← critical
languageCode = "en-gb"
title = "My Research Notes"
publishDir = "public"                    # keep default
theme = "hugo-PaperMod"

# Number of posts per page
[pagination]
  pagerSize = 9


[params]
  description = "Exploring the frontiers of AI research and applications"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  homeInfoParams = { Title = "Welcome", Content = "Exploring the frontiers of AI research and applications" }

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/myresearchnotes"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/myresearchnotes"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/myresearchnotes"
