baseURL     = "https://13ryanC.github.io/"
languageCode = "en-gb"
title       = "My Research Notes"
publishDir  = "public"
theme       = "hugo-PaperMod"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[menu]

  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"
    weight     = 10

  [[menu.main]]
    identifier = "series"
    name       = "Series"
    url        = "/series/"
    weight     = 20

  [[menu.main]]
    identifier = "search"
    name       = "Search"
    url        = "/search/"
    weight     = 30

  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "/tags/"
    weight     = 40

  [[menu.main]]
    identifier = "faq"
    name       = "FAQ"
    url        = "/faq/"
    weight     = 50

# Number of posts per page
[pagination]
  pagerSize = 20 

############################
# 1. Site-wide PaperMod flags
############################
[params]
  math               = true
  mermaid           = true
  ShowCodeCopyButtons = true     # clipboard icon on every ``` fence
  description        = "Exploring the frontiers of AI research and applications"
  defaultTheme       = "auto"
  ShowReadingTime    = true
  ShowShareButtons   = true

  homeInfoParams = { Title = "Welcome", Content = "Exploring the frontiers of AI research and applications" }

  [[params.socialIcons]]
    name = "twitter"
    url  = "https://twitter.com/myresearchnotes"

  [[params.socialIcons]]
    name = "github"
    url  = "https://github.com/13ryanC"

  [[params.socialIcons]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/myresearchnotes"

[params.assets]
  customCSS = [
    "css/math-table.css",    # (if you added this earlier)
    "css/math-scroll.css",    #  ← NEW
    "css/pagination.css"      # styles for custom pagination
  ]
  customJS = [
    "js/mathjax.js",
    "js/vendor/mermaid.min.js",
    "js/vendor/svg-pan-zoom.min.js",
    "js/mermaid-bootstrap.js"
  ]

########################################
# 2. Goldmark & syntax-highlight tweaks
########################################
[markup]
  defaultMarkdownHandler = 'goldmark'

  [markup.goldmark.renderer]
    unsafe = true         # ←  allow raw HTML

  [markup.goldmark.parser]
    attribute = true

  [markup.highlight]
    codeFences = true            # colourise ``` fences
    noClasses  = false           # keep CSS classes so PaperMod’s palette applies
    guessSyntax = false          # speed boost; flip to true if you omit languages

  [markup.goldmark.extensions]
    footnote = true            # optional, useful for citations/notes
    # passthrough = true
